### PR TITLE
Add new flag -service-url to support target and access control selection

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new flag `-service-url` that allows override of the '-hostname' in addition to allowing a caller to specify other parts of the url, such as the access_token parameters.

This change updates the logic in ws.go to use URLs rather than static url field parameters to functions.

These changes support the e2e monitoring with access token effort. The idea is that a tool to get an access token URL could pass in the "-service-url" via the environment.

For example:

```
monitoring-token \
  -monitoring-signer-key=key-file \
  -machine=${machine} -service=ndt/ndt5 -- \
  ndt5-client -throttle=262144 -protocol=ndt5+wss
```

`monitoring-token` negotiates a monotiring access token from the locate service, and passes the SERVICE_URL via the environment before executing ndt5-client.

The alternative strategy is to only change ndt5-client to use `flagx.ArgsFromEnv` and have the monitoring-token command pass the `hostname` and `access_token` through the environment. This approach felt less desirable, b/c the goal is for clients to directly use the URLs provided by the locate service.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt5-client-go/8)

### CODE REVIEW

**Review by robertodauria — COMMENTED** [review]
I'm very much in favor of using the URL provided by the locate service directly, and I like how the code became simpler by using a `URL`.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt5-client-go/8#-:-M4_Wx7f5_lJ3iFg0bVg:bspvfuu)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

**Review by stephen-soltesz — COMMENTED** [review]
Okay -- let's do it. PR is ready for review.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt5-client-go/8#-:-M4_eX8FEPVilW8Px536:b-rtah7a)* status: 0 of 1 approvals obtained

**Review by robertodauria — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt5-client-go/8#-:-M4_ewxGAR8hmWRsuXEK:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt5-client-go/8)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[ws.go, line 78 at r1](https://reviewable.io/reviews/m-lab/ndt5-client-go/8#-M4_wbMA2pMlXHxWmsCg:-M4_wbMA2pMlXHxWmsCh:b-vspuxp) ([raw file](https://github.com/m-lab/ndt5-client-go/blob/57b6aacf5ec0e6a5e8b52e9002b396d4ab73a89f/ws.go#L78)):*
> ```Go
> // DialEx is the extended WebSocket dial function
> func (cf *WSConnectionsFactory) DialEx(
> 	ctx context.Context, address, path, userAgent, wsProtocol string,
> ```

Looking this over once more I happen to notice that the `userAgent` and `wsProtocol` parameters have always been in the wrong order wrt the callers. So, I've swapped them to provide the correct / intended values for each.

I don't think this has impacted the client or server b/c the ndt5 server does not enforce these values in any way as (I think) the ndt7 server does.

**Pull request merged**
